version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      - node/test
      - sudo apt-get update -y && sudo apt-get install -y unzip xvfb libxi6 libgconf-2-4 default-jdk
